"""empty message

Revision ID: 883de6f9880d
Revises: f60a557506c9
Create Date: 2026-03-16 20:22:24.850521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883de6f9880d'
down_revision = 'f60a557506c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
